package reporter

import (
	"bytes"
	"fmt"
	"strings"

	"github.com/jung-kurt/gofpdf"
	"github.com/wcharczuk/go-chart/v2"
	"github.com/wcharczuk/go-chart/v2/drawing"
)

// GeneratePDF generates a professional PDF report with cover page, executive summary,
// and detailed per-finding pages with code snippets and remediation.
func GeneratePDF(filename string, findings []Finding, summary ReportSummary, riskScore RiskScore) error {
	pdf := gofpdf.New("P", "mm", "A4", "") // Portrait for readability

	pdf.SetFooterFunc(func() {
		pdf.SetY(-12)
		pdf.SetFont("Helvetica", "I", 8)
		pdf.SetTextColor(150, 150, 150)
		pdf.CellFormat(0, 5, fmt.Sprintf("SentryQ Security Report | Page %d of {nb}", pdf.PageNo()), "", 0, "C", false, 0, "")
	})
	pdf.AliasNbPages("")

	pdf.SetAutoPageBreak(true, 18)

	// ——— Cover Page ———
	pdf.AddPage()
	pdf.SetFillColor(15, 23, 42) // Dark slate
	pdf.Rect(0, 0, 210, 297, "F")

	// Accent bar
	pdf.SetFillColor(59, 130, 246) // Blue accent
	pdf.Rect(0, 0, 210, 4, "F")

	// Title
	pdf.SetTextColor(255, 255, 255)
	pdf.SetFont("Helvetica", "B", 36)
	pdf.SetY(80)
	pdf.CellFormat(210, 15, "SentryQ", "", 1, "C", false, 0, "")
	pdf.SetFont("Helvetica", "", 16)
	pdf.SetTextColor(148, 163, 184)
	pdf.CellFormat(210, 10, "AI-Powered Security Scan Report", "", 1, "C", false, 0, "")
	pdf.Ln(20)

	targetDir := sanitizePDFText(summary.TargetDirectory)
	scanDate := sanitizePDFText(summary.ScanDate)
	scannerVersion := sanitizePDFText(summary.ScannerVersion)

	pdf.SetFont("Helvetica", "", 11)
	pdf.SetTextColor(203, 213, 225)
	pdf.CellFormat(210, 7, fmt.Sprintf("Target: %s", targetDir), "", 1, "C", false, 0, "")
	pdf.CellFormat(210, 7, fmt.Sprintf("Date: %s", scanDate), "", 1, "C", false, 0, "")
	pdf.CellFormat(210, 7, fmt.Sprintf("Scanner: v%s", scannerVersion), "", 1, "C", false, 0, "")
	pdf.Ln(20)

	// Risk Score
	scoreColor := getScoreColor(riskScore.Level)
	pdf.SetFillColor(scoreColor[0], scoreColor[1], scoreColor[2])
	boxW, boxH := 80.0, 40.0
	boxX := (210 - boxW) / 2
	pdf.RoundedRect(boxX, pdf.GetY(), boxW, boxH, 5, "1234", "F")
	pdf.SetFont("Helvetica", "B", 32)
	pdf.SetTextColor(255, 255, 255)
	pdf.SetY(pdf.GetY() + 5)
	pdf.CellFormat(210, 14, fmt.Sprintf("%d / 100", riskScore.Score), "", 1, "C", false, 0, "")
	pdf.SetFont("Helvetica", "", 12)
	pdf.CellFormat(210, 8, riskScore.Level, "", 1, "C", false, 0, "")

	// Footer
	pdf.SetY(260)
	pdf.SetFont("Helvetica", "I", 9)
	pdf.SetTextColor(100, 116, 139)
	pdf.CellFormat(210, 6, "Generated by SentryQ - AI-Powered Security Scanner", "", 1, "C", false, 0, "")

	// ——— Executive Summary Page ———
	pdf.AddPage()
	addPortraitHeader(pdf, "Executive Summary")

	// Stats table
	pdf.SetFont("Helvetica", "B", 9)
	pdf.SetFillColor(55, 48, 163)
	pdf.SetTextColor(255, 255, 255)
	colWidths := []float64{38, 38, 38, 38, 38}
	headers := []string{"Total", "Critical", "High", "Medium", "Low"}
	for i, h := range headers {
		pdf.CellFormat(colWidths[i], 9, h, "1", 0, "C", true, 0, "")
	}
	pdf.Ln(-1)

	pdf.SetFont("Helvetica", "B", 13)
	values := []int{summary.TotalFindings, summary.CriticalCount, summary.HighCount, summary.MediumCount, summary.LowCount}
	colors := [][3]int{{240, 240, 245}, {254, 226, 226}, {255, 237, 213}, {254, 252, 232}, {236, 254, 255}}
	textColors := [][3]int{{30, 30, 60}, {220, 38, 38}, {234, 88, 12}, {161, 98, 7}, {8, 145, 178}}
	for i, v := range values {
		pdf.SetFillColor(colors[i][0], colors[i][1], colors[i][2])
		pdf.SetTextColor(textColors[i][0], textColors[i][1], textColors[i][2])
		pdf.CellFormat(colWidths[i], 12, fmt.Sprintf("%d", v), "1", 0, "C", true, 0, "")
	}
	pdf.Ln(15)

	// Severity Chart
	chartBytes, err := generateSeverityChart(summary)
	if err == nil {
		chartName := fmt.Sprintf("chart_%d", summary.TotalFindings)
		rs := bytes.NewReader(chartBytes)
		pdf.RegisterImageOptionsReader(chartName, gofpdf.ImageOptions{ImageType: "PNG"}, rs)
		pdf.ImageOptions(chartName, 120, pdf.GetY(), 75, 0, false, gofpdf.ImageOptions{ImageType: "PNG"}, 0, "")
	}

	// Narrative summary
	pdf.SetTextColor(30, 30, 60)
	pdf.SetFont("Helvetica", "", 10)
	pdf.SetX(15)
	pdf.MultiCell(100, 5.5, sanitizePDFText(fmt.Sprintf(
		"This scan analyzed '%s' and discovered %d potential security issues. "+
			"%d are Critical (immediate action required), %d are High, %d are Medium, and %d are Low. "+
			"%d findings were validated or discovered by AI analysis.",
		summary.TargetDirectory, summary.TotalFindings,
		summary.CriticalCount, summary.HighCount, summary.MediumCount, summary.LowCount,
		summary.AIValidatedCount)), "", "L", false)
	pdf.Ln(10)

	// ——— Table of Contents ———
	reachable, _, falsePositives := SplitFindingsThreeWay(findings)

	pdf.AddPage()
	addPortraitHeader(pdf, "Table of Contents")
	pdf.SetFont("Helvetica", "", 10)
	pdf.SetTextColor(30, 30, 60)
	tocEntries := []struct{ label string; count int }{
		{"Executive Summary", 0},
		{"Detailed Findings", len(reachable)},
	}
	if len(falsePositives) > 0 {
		tocEntries = append(tocEntries, struct{ label string; count int }{"Manual Review — Potential False Positives", len(falsePositives)})
	}
	// Severity breakdown in TOC
	sevGroups := map[string]int{}
	for _, f := range reachable {
		sevGroups[strings.ToLower(f.Severity)]++
	}
	for _, sev := range []string{"critical", "high", "medium", "low", "info"} {
		if n := sevGroups[sev]; n > 0 {
			tocEntries = append(tocEntries, struct{ label string; count int }{
				fmt.Sprintf("  — %s findings", strings.Title(sev)), n,
			})
		}
	}
	for _, e := range tocEntries {
		pdf.SetX(20)
		if e.count > 0 {
			pdf.CellFormat(150, 7, sanitizePDFText(e.label), "", 0, "L", false, 0, "")
			pdf.SetFont("Helvetica", "B", 10)
			pdf.CellFormat(25, 7, fmt.Sprintf("%d", e.count), "", 1, "R", false, 0, "")
			pdf.SetFont("Helvetica", "", 10)
		} else {
			pdf.CellFormat(175, 7, sanitizePDFText(e.label), "", 1, "L", false, 0, "")
		}
	}
	pdf.Ln(5)

	// ——— Detailed Findings ———
	pdf.AddPage()
	addPortraitHeader(pdf, "Detailed Findings")

	for _, f := range reachable {
		drawFindingDetail(pdf, f)
	}

	// ——— False Positives / Manual Review ———
	if len(falsePositives) > 0 {
		pdf.AddPage()
		addPortraitHeader(pdf, "Manual Review - Potential False Positives")
		pdf.SetFont("Helvetica", "I", 9)
		pdf.SetTextColor(120, 120, 140)
		pdf.MultiCell(0, 5, "The following findings were flagged as potential false positives by AI/ML analysis.", "", "L", false)
		pdf.Ln(4)

		for _, f := range falsePositives {
			drawFindingDetail(pdf, f)
		}
	}

	return pdf.OutputFileAndClose(filename)
}

// drawFindingDetail renders a single finding as a detailed block with code and remediation.
func drawFindingDetail(pdf *gofpdf.Fpdf, f Finding) {
	// Check if we need a new page (at least 80mm needed for a finding block)
	if pdf.GetY() > 220 {
		pdf.AddPage()
		addPortraitHeader(pdf, "Detailed Findings (continued)")
	}

	leftMargin := 15.0
	contentWidth := 180.0

	// ── Finding Header Bar ──
	sevColor := getSeverityColor(f.Severity)
	pdf.SetFillColor(sevColor[0], sevColor[1], sevColor[2])
	pdf.Rect(leftMargin, pdf.GetY(), contentWidth, 8, "F")
	pdf.SetFont("Helvetica", "B", 9)
	pdf.SetTextColor(255, 255, 255)
	pdf.SetX(leftMargin + 2)
	headerText := fmt.Sprintf("#%d  |  %s  |  %s  |  Line %s",
		f.SrNo,
		sanitizePDFText(truncateString(f.IssueName, 50)),
		strings.ToUpper(f.Severity),
		f.LineNumber)
	pdf.CellFormat(contentWidth-4, 8, headerText, "", 1, "L", false, 0, "")

	// ── File Path ──
	pdf.SetFillColor(245, 245, 250)
	pdf.Rect(leftMargin, pdf.GetY(), contentWidth, 6, "F")
	pdf.SetFont("Helvetica", "", 7.5)
	pdf.SetTextColor(80, 80, 120)
	pdf.SetX(leftMargin + 2)
	fileInfo := fmt.Sprintf("File: %s", sanitizePDFText(f.FilePath))
	if f.CWE != "" {
		fileInfo += fmt.Sprintf("  |  %s", extractCWEID(f.CWE))
	}
	if f.OWASP != "" {
		owaspDisplay := NormalizeOWASP(f.OWASP)
		if owaspDisplay == "" {
			owaspDisplay = truncateString(f.OWASP, 20)
		}
		fileInfo += fmt.Sprintf("  |  OWASP %s", sanitizePDFText(owaspDisplay))
	}
	if f.Source != "" {
		fileInfo += fmt.Sprintf("  |  Source: %s", sanitizePDFText(truncateSource(f.Source)))
	}
	pdf.CellFormat(contentWidth-4, 6, fileInfo, "", 1, "L", false, 0, "")

	// ── Description ──
	pdf.SetFont("Helvetica", "B", 8)
	pdf.SetTextColor(55, 48, 163)
	pdf.SetX(leftMargin)
	pdf.CellFormat(contentWidth, 6, "Description", "", 1, "L", false, 0, "")
	pdf.SetFont("Helvetica", "", 8)
	pdf.SetTextColor(30, 30, 60)
	pdf.SetX(leftMargin)
	descText := sanitizePDFText(truncateString(f.Description, 1000))
	pdf.MultiCell(contentWidth, 4.2, descText, "", "L", false)
	pdf.Ln(2)

	// ── Vulnerable Code Snippet ──
	if f.CodeSnippet != "" {
		if pdf.GetY() > 210 {
			pdf.AddPage()
			addPortraitHeader(pdf, "Detailed Findings (continued)")
		}
		pdf.SetFont("Helvetica", "B", 8)
		pdf.SetTextColor(220, 38, 38)
		pdf.SetX(leftMargin)
		pdf.CellFormat(contentWidth, 6, "Vulnerable Code", "", 1, "L", false, 0, "")

		// Code block background
		codeText := sanitizePDFText(truncateString(f.CodeSnippet, 400))
		codeLines := pdf.SplitText(codeText, contentWidth-8)
		codeH := float64(len(codeLines))*3.5 + 4
		if codeH > 50 {
			codeH = 50
		}
		pdf.SetFillColor(13, 17, 23) // Dark code background
		pdf.Rect(leftMargin, pdf.GetY(), contentWidth, codeH, "F")
		pdf.SetFont("Courier", "", 7)
		pdf.SetTextColor(201, 209, 217)
		pdf.SetXY(leftMargin+3, pdf.GetY()+2)
		maxCodeLines := int((codeH - 4) / 3.5)
		if maxCodeLines > len(codeLines) {
			maxCodeLines = len(codeLines)
		}
		if maxCodeLines > 0 {
			pdf.MultiCell(contentWidth-6, 3.5, strings.Join(codeLines[:maxCodeLines], "\n"), "", "L", false)
		}
		pdf.Ln(2)
	}

	// ── Remediation ──
	if f.Remediation != "" {
		if pdf.GetY() > 250 {
			pdf.AddPage()
			addPortraitHeader(pdf, "Detailed Findings (continued)")
		}
		pdf.SetFont("Helvetica", "B", 8)
		pdf.SetTextColor(22, 163, 74)
		pdf.SetX(leftMargin)
		pdf.CellFormat(contentWidth, 6, "Remediation", "", 1, "L", false, 0, "")
		pdf.SetFont("Helvetica", "", 8)
		pdf.SetTextColor(30, 30, 60)
		pdf.SetX(leftMargin)
		remText := sanitizePDFText(truncateString(f.Remediation, 1000))
		pdf.MultiCell(contentWidth, 4.2, remText, "", "L", false)
		pdf.Ln(2)
	}

	// ── Fixed Code (AI-generated) ──
	if f.FixedCode != "" {
		if pdf.GetY() > 210 {
			pdf.AddPage()
			addPortraitHeader(pdf, "Detailed Findings (continued)")
		}
		pdf.SetFont("Helvetica", "B", 8)
		pdf.SetTextColor(22, 163, 74)
		pdf.SetX(leftMargin)
		pdf.CellFormat(contentWidth, 6, "Secure Code Fix", "", 1, "L", false, 0, "")

		fixText := sanitizePDFText(truncateString(f.FixedCode, 400))
		fixLines := pdf.SplitText(fixText, contentWidth-8)
		fixH := float64(len(fixLines))*3.5 + 4
		if fixH > 50 {
			fixH = 50
		}
		pdf.SetFillColor(13, 30, 23) // Dark green code background
		pdf.Rect(leftMargin, pdf.GetY(), contentWidth, fixH, "F")
		pdf.SetFont("Courier", "", 7)
		pdf.SetTextColor(74, 222, 128)
		pdf.SetXY(leftMargin+3, pdf.GetY()+2)
		maxFixLines := int((fixH - 4) / 3.5)
		if maxFixLines > len(fixLines) {
			maxFixLines = len(fixLines)
		}
		if maxFixLines > 0 {
			pdf.MultiCell(contentWidth-6, 3.5, strings.Join(fixLines[:maxFixLines], "\n"), "", "L", false)
		}
		pdf.Ln(2)
	}

	// ── Exploit PoC ──
	if f.ExploitPoC != "" && f.ExploitPoC != "N/A" {
		if pdf.GetY() > 250 {
			pdf.AddPage()
			addPortraitHeader(pdf, "Detailed Findings (continued)")
		}
		pdf.SetFont("Helvetica", "B", 8)
		pdf.SetTextColor(220, 38, 38)
		pdf.SetX(leftMargin)
		pdf.CellFormat(contentWidth, 6, "Exploit Proof of Concept", "", 1, "L", false, 0, "")
		pdf.SetFont("Courier", "", 7)
		pdf.SetTextColor(80, 80, 80)
		pdf.SetX(leftMargin)
		pocText := sanitizePDFText(truncateString(f.ExploitPoC, 800))
		pdf.MultiCell(contentWidth, 3.5, pocText, "", "L", false)
		pdf.Ln(2)
	}

	// ── Taint Flow ──
	if len(f.ExploitPath) > 0 {
		if pdf.GetY() > 240 {
			pdf.AddPage()
			addPortraitHeader(pdf, "Detailed Findings (continued)")
		}
		pdf.SetFont("Helvetica", "B", 8)
		pdf.SetTextColor(99, 102, 241)
		pdf.SetX(leftMargin)
		pdf.CellFormat(contentWidth, 6, "Taint Flow Analysis", "", 1, "L", false, 0, "")
		pdf.SetFont("Helvetica", "", 7.5)
		for i, step := range f.ExploitPath {
			label := fmt.Sprintf("Hop %d", i)
			if i == 0 {
				label = "Source"
				pdf.SetTextColor(220, 38, 38)
			} else if i == len(f.ExploitPath)-1 {
				label = "Sink"
				pdf.SetTextColor(185, 28, 28)
			} else {
				pdf.SetTextColor(80, 80, 120)
			}
			pdf.SetX(leftMargin + 2)
			pdf.CellFormat(18, 4.5, label+":", "", 0, "L", false, 0, "")
			pdf.SetTextColor(30, 30, 60)
			pdf.MultiCell(contentWidth-20, 4.5, sanitizePDFText(truncateString(step, 120)), "", "L", false)
		}
		pdf.Ln(2)
	}

	// ── Separator ──
	pdf.SetDrawColor(200, 200, 220)
	pdf.SetLineWidth(0.2)
	pdf.Line(leftMargin, pdf.GetY(), leftMargin+contentWidth, pdf.GetY())
	pdf.Ln(5)
}

func generateSeverityChart(summary ReportSummary) ([]byte, error) {
	values := []chart.Value{}

	if summary.CriticalCount > 0 {
		values = append(values, chart.Value{Value: float64(summary.CriticalCount), Label: "Critical", Style: chart.Style{FillColor: drawing.ColorFromHex("dc2626")}})
	}
	if summary.HighCount > 0 {
		values = append(values, chart.Value{Value: float64(summary.HighCount), Label: "High", Style: chart.Style{FillColor: drawing.ColorFromHex("ea580c")}})
	}
	if summary.MediumCount > 0 {
		values = append(values, chart.Value{Value: float64(summary.MediumCount), Label: "Medium", Style: chart.Style{FillColor: drawing.ColorFromHex("ca8a04")}})
	}
	if summary.LowCount > 0 {
		values = append(values, chart.Value{Value: float64(summary.LowCount), Label: "Low", Style: chart.Style{FillColor: drawing.ColorFromHex("16a34a")}})
	}

	if summary.InfoCount > 0 {
		values = append(values, chart.Value{Value: float64(summary.InfoCount), Label: "Info", Style: chart.Style{FillColor: drawing.ColorFromHex("4b5563")}})
	}

	if len(values) == 0 {
		return nil, fmt.Errorf("no findings to chart")
	}

	pie := chart.PieChart{
		Width:  400,
		Height: 400,
		Values: values,
	}

	buffer := bytes.NewBuffer([]byte{})
	err := pie.Render(chart.PNG, buffer)
	if err != nil {
		return nil, err
	}
	return buffer.Bytes(), nil
}

func truncateString(s string, maxLen int) string {
	runes := []rune(s)
	if len(runes) <= maxLen {
		return s
	}
	return string(runes[:maxLen]) + "..."
}

func truncateSource(s string) string {
	switch {
	case strings.Contains(s, "ai"):
		return "AI"
	case strings.Contains(s, "semgrep"):
		return "Semgrep"
	case strings.Contains(s, "secret"):
		return "Secret"
	default:
		return "Rules"
	}
}

// extractCWEID extracts just the CWE-NNN ID from a full CWE string.
func extractCWEID(cwe string) string {
	if cwe == "" {
		return ""
	}
	if idx := strings.Index(cwe, ":"); idx > 0 {
		return strings.TrimSpace(cwe[:idx])
	}
	return truncateString(cwe, 18)
}

func addPortraitHeader(pdf *gofpdf.Fpdf, title string) {
	pdf.SetFont("Helvetica", "B", 16)
	pdf.SetTextColor(55, 48, 163)
	pdf.CellFormat(0, 10, title, "", 1, "L", false, 0, "")
	pdf.SetDrawColor(55, 48, 163)
	pdf.SetLineWidth(0.5)
	pdf.Line(10, pdf.GetY(), 200, pdf.GetY())
	pdf.Ln(6)
}

func getScoreColor(level string) [3]int {
	switch level {
	case "Critical Risk":
		return [3]int{220, 38, 38}
	case "High Risk":
		return [3]int{234, 88, 12}
	case "Medium Risk":
		return [3]int{202, 138, 4}
	default:
		return [3]int{22, 163, 74}
	}
}

func getSeverityColor(sev string) [3]int {
	switch strings.ToLower(sev) {
	case "critical":
		return [3]int{220, 38, 38}
	case "high":
		return [3]int{234, 88, 12}
	case "medium":
		return [3]int{180, 140, 20}
	case "low":
		return [3]int{8, 145, 178}
	default:
		return [3]int{107, 114, 128}
	}
}

// sanitizePDFText prepares text for the PDF library, which mostly supports ISO-8859-1.
func sanitizePDFText(text string) string {
	var sb strings.Builder
	for _, r := range text {
		if r < 32 && r != '\t' && r != '\n' && r != '\r' {
			continue
		}
		sb.WriteRune(r)
	}
	text = sb.String()

	replacer := strings.NewReplacer(
		"\u2014", "-",
		"\u2013", "-",
		"\u2026", "...",
		"\u2022", "*",
		"\u00A0", " ",
		"\u2018", "'",
		"\u2019", "'",
		"\u201C", "\"",
		"\u201D", "\"",
	)
	text = replacer.Replace(text)

	var finalSb strings.Builder
	for _, r := range text {
		if r > 126 {
			finalSb.WriteRune('?')
		} else {
			finalSb.WriteRune(r)
		}
	}

	return finalSb.String()
}
